### ISSUE TITLE
"Browse" buttoon for the Path to custom css

### ISSUE THREAD

**Issue by Djagga-Djagga** [numirias/paxmod#17]
Subj.

**Comment by numirias** [comment]
The custom CSS was implemented as a text field with a path instead of an upload dialog to support people who frequently (often programmatically) change their custom CSS. This way, they don't need go to the settings an re-upload the changed file after every modification.

But I can totally see why you'd want to upload CSS instead of entering the path (esp. to use it across multiple systems), so I'll see that I add that feature.

**Comment by numirias** [comment]
I decided to add a code field instead to paste your custom CSS into (see release [v2.3](https://github.com/numirias/paxmod/releases/tag/v2.3)). The user experience here shouldn't be much different from uploading a file.
