### ISSUE TITLE
Firefox 61 - don't work 

### ISSUE THREAD

**Issue by Lukasz87** [numirias/paxmod#21]
Hi,
Today after update to FF 61, paxmod don't work.
All tabs i have in one line.
I downgrade to FF 59 and start to work.

**Comment by numirias** [comment]
Thanks for checking out Paxmod!

What OS and Firefox release are you using?

Can you make sure:

- You're using either FF Developer or Nightly
- At `about:config`, `xpinstall.signatures.required` is set to `false`
- At `about:config`, `extensions.legacy.enabled` is set to `true`
- You've installed the [latest](https://github.com/numirias/paxmod/releases/tag/v2.5) version of Paxmod
- You've tried to remove and re-install the addon.

**Comment by Lukasz87** [comment]
Os: Ubuntu 18.10 , FF 61.0 updated from repository from v 60 to 61
I have setup:
At about:config, xpinstall.signatures.required is set to false
At about:config, extensions.legacy.enabled is set to true
and use paxmod 2.5

You've tried to remove and re-install the addon ---> no i don't try  this

**Comment by Lukasz87** [comment]
Now i downgrade:

Name 	Firefox
Version 	59.0.2
Build ID 	20180406121424
Update History 	
User Agent 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
OS 	Linux 4.15.11-041511-generic

but i don't use  Developer or Nightly. In FF 60 work on normal version.

**Comment by numirias** [comment]
Unfortunately, Firefox has dropped support for unsupported extensions in newer versions of the standard release, so your only option to continue using Paxmod in the future will be switching to Developer or Nightly.

As an aside, I'd strongly recommend against keeping FF downgraded because you might be missing important security updates that keep you safe.
