### ISSUE TITLE
on 70b not working

### ISSUE THREAD

**Issue by olaims** [numirias/paxmod#38]
I just updated firefox to 70b and it seems not to work anymore :(

**Comment by olaims** [comment]
is there anyway to download an old firefox developer version? Searching on google I cannot find it :(

**Comment by numirias** [comment]
Thanks for reporting!

> I just updated firefox to 70b and it seems not to work anymore :(

The extension runs fine for me on Developer `70.0b7` and Nightly `71.0a1`. Are you sure your update didn't just disable the addon (and requires your to re-enable it) or changed some of the settings required per the README? Could you double-check, and if it still doesn't work, give additional information about your OS?

> is there anyway to download an old firefox developer version? Searching on google I cannot find it :(

You absolutely shouldn't run an outdated version of Firefox because then you're missing important security patches.

**Comment by olaims** [comment]
I'm now in the last Nightly and it works.

1. I just opened the developer again
2. accepted a new updated
3. closed it
4. opened it again
5. and now it works :/

Strange. I changed nothing and the other day I was trying also restarting and checking the settings and everything was as it should.
