### ISSUE TITLE
Multi-row tabs no longer working on FF Developer 71.0b1

### ISSUE THREAD

**Issue by KorinFlakes** [numirias/paxmod#42]
As the title states, after my FF updated the multi row tabs have turned into a single row with arrows to scroll back and forth. I've tried fiddling with the settings of paxmod and updating to the version released 10 or so days ago, neither of which worked.

The addon it self is in part working, the dynamic colours still work and the sizing of the tabs works but it won't add a second row.

Also I'm on Windows 10 (Build 18362) atm if that's a factor.

**Comment by numirias** [comment]
I think this is because I patched it for a *later* build that is out on Nightly, but not yet on Developer.

You can:
- Install [Paxmod 3.1](https://github.com/numirias/paxmod/releases/tag/v3.1) and go to `about:addons` > *Paxmod* > *Details*/*Manage* and **turn off** automatic updates. Once the add-on breaks again with a later FF update, just re-enable auto updates.

or

- Use Firefox Nightly instead.

Let me know if you have success with any of these measures. Unfortunately I'm not sure how to cleanly differentiate between Firefox Developer and Nightly in an add-on manifest.

**Comment by KorinFlakes** [comment]
I tried using v3.1 but it wasn't working so I just downloaded Nightly and just imported everything over to that. It's working like a charm now, thank you for your help.

**Comment by chseip** [comment]
Yep, neither 3.1 nor 3.2 are working in FF Developer 71.0b1. I'm too lazy to switch to Nightly...

**Comment by numirias** [comment]
@chseip Try 3.0. The only thing that changed to 3.1 was the auto-updating mechanism.

**Comment by chseip** [comment]
Not working either.

**Comment by fraynaud33** [comment]
Same problem for me. 3.0 or 3.1 doesn't work on 70.0b7 on Windows10.

**Comment by numirias** [comment]
@chseip @fraynaud33 @KorinFlakes Please check if it works by setting `layout.css.shadow-parts.enabled` to `true` in `about:config`.

**Comment by chseip** [comment]
Works like a charm with 3.2 for me, finally, thanks! :-)

**Comment by fraynaud33** [comment]
Great. It works perfectly. Thanks !
