### ISSUE TITLE
2000+ Tabs - No content visible anymore. Maximum rows setting is needed

### ISSUE THREAD

**Issue by propagare** [numirias/paxmod#48]
Hello, 

I am using the https://github.com/mozilla/multi-account-containers plugin to manage more than a dozens of tab groups.

My last multirow userChrome.css was broken again with the new Firefox update. I discovered your great addon, switched to the Nightly for it.

Is there maybe a workaround to set a max number of tab rows for ppl like me to have some visible content beside those numbers of tabs?

Thanks in advance.

**Comment by Delta2401** [comment]
Not sure 2000 is manageable even when this addon was bugfree a month back. Do you use multiple windows? You might need to hide large clumps of those tabs on and off, via hide tab; but for that huge number, I would probably just use something like Session Boss; and have windows in each of your groups, and save that session window to load or modify whenever you want that chunk. These are just ideas I would be spitballing.

I think the most I ever had was a couple hundred over 4 windows. The last firefox update really broke the space limiter for each tab to hold whatever the size of the tab title was, so unless you want to us an extension like "tab mix - tab rename" on every single tab to shrink it; which for thousands, it might not be practical. But even if you had a logo on each tab and nothing else, 2000 would probably still fill a window a couple times over. Either way, most of us are awaiting a hopeful this addon can get fixed for tab sizes; but it seems you have more need than that.

**Comment by jtagcat** [comment]
I'd not get stuck around 2k tabs. Even with ~50 tabs it gets messy for smaller screen laptops. I have already mentioned this issue in an another issue: even limiting to say 2-3 rows is sensible.

**Comment by numirias** [comment]
ℹ️ If you want more tabs per row, you can set *Default tab width* down to 0% and set *Min. tab width* to the lowest value you're comfortable with.

I don't think I can implement a max number of tab rows, because then the tab box would need to be scrollable and scroll automatically when you're switching to a tab whose label is currently in an invisible area. This would require Javascript, and the UI modifications are currently CSS-only and I really want to keep it that way.

What I might be able to do is introduce a feature that shrinks the tab height dynamically. But you may also consider a different workflow than having thousands of tabs open, e.g. with bookmarks and toolbars.

**Comment by numirias** [comment]
@mjk-gh Thanks for your comment. The latest release implements a max number of tab rows. Feel free to open a new issue if it doesn't work for you.

**Comment by mjk-gh** [comment]
@numirias Thanks for the fix!

The actual limitation to `n` rows seems to work, but without my userChrome.css[1]
snippet, you cannot scroll within the tab area using the scrollwheel. Ctrl-PgUp/Dn
and Alt-1..9 (or Ctrl-1..9) do work, and the scrollbar for the tab area is also showing,
but using the scrollwheel does not do anything.

I tried both Fx 76 and Fx 77 (Linux, amd64).

[1]  (which still has to be in the profile folder and has no effect on tab
area scrollability when put in paxmod's "Custom CSS")
