### ISSUE TITLE
Windows 10 user with issues on firefox developer edition

### ISSUE THREAD

**Issue by hashburger420** [numirias/paxmod#5]
Version 	61.0b2
Build ID 	20180503152818
Update Channel 	aurora
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
OS 	Windows_NT 10.0

The extension appears to be doing nothing.  Configuration page is available, and loading defaults seems to load what is correct values but there is no change in theme or appearance.  I am using a seperate profile for the development browser from the normal firefox browser, as is default for firefox developer edition.

Paxmod	1.4	true	paxmod@numirias

also this is my first time submitting an issue on github for the record, but I'm willing to follow through on what appears to be a great theme.

**Comment by numirias** [comment]
Thanks for reporting!

I think I can reproduce the issue in FF61+. I'll let you know when I got it fixed.

**Comment by numirias** [comment]
@nt1m Sorry to bother you here. Are you familiar with any recent API changes for inlined webextension experiments?

With FF61, paxmod stopped working, and I can reproduce the same problem with an unrelated extension which leads me to believe this might be due to a change on Mozilla's end.

If you install paxmod in most recent FF61 you get:

    TypeError: browser.stylesheet is undefined

(Curiously, this error does **not** occur when testing the extension via `web-ext`, only when installing the `.xpi` manually.)

The error indicates that `browser.stylesheet` isn't available (that's the inlined experiment API) but I can't figure out why it stopped loading the API.

Also I get an equivalent error when trying [this extension](https://github.com/mozilla/gecko/tree/central/testing/talos/talos/tests/tabswitch). The extension ships an experiment API called `tps` and after installing it raises:

    TypeError: browser.tps is undefined

Do you have a tip what might cause this or how to investigate?

**Comment by numirias** [comment]
Okay I investigated this and @icejr was right.

For some reason you *initially* need to set `extensions.legacy.enabled` to `true`. Then re-install paxmod. Otherwise, Firefox doesn't detect the bundled API experiment.

**Comment by hashburger420** [comment]
I got it working after doing some non-poweruser fiddling now, had to re-open the dev browser about 3 times over.  After removal of paxmod and readdition, restore defaults appeared to do nothing until re-initiating the browser a 3rd time, probably due to not having a fresh install.  But it works now.

**Comment by nt1m** [comment]
@numirias Yes, the legacy add-on pref needs to be enabled. See: https://searchfox.org/mozilla-central/rev/f30847c12e5fb13791401ed4330ced3e1b9c8d81/toolkit/components/extensions/Extension.jsm#1417-1420
