### ISSUE TITLE
Look in to signing outside of AMO.

### ISSUE THREAD

**Issue by jtagcat** [numirias/paxmod#56]
Paxmod relies on an "experimental API" that ships bundled with the add-on. Unfortunately, this means Mozilla won't sign the extension anymore and therefore it can't be distributed over the official channels.

Yes and no.

Mozilla won't sign the extension (through AMO), but iirc we can sign it ourselves.

iirc to sign it yourself, you need to have 2fa. Not sure what is accepted as 2fa (security questions, lol), I have yubikeys (what rn are the gold standard, what is also widely accepted), I'll give it a try.

https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

**Comment by numirias** [comment]
Would be nice. But do you have any reference to Mozilla supporting self-signing of addons? All ways described in the docs involve having it signed by Mozilla, which we can't do.

**Comment by jtagcat** [comment]
I am not sure, I will ask around in Mozilla and try to do something.

I think it is possible, just look at this for example:
![image](https://user-images.githubusercontent.com/38327267/79043974-2158ef00-7bf2-11ea-8c0e-bc4da968506f.png)
Just a simple warning to press ok to, should actually simplify the installation, now to hope is that it supports experimental APIs.

**Comment by numirias** [comment]
@jtagcat I think you're confusing something here. Your screenshot just shows the warning you get when a website that's not AMO triggers an addon installation. It's the same when you install Paxmod from the releases page on Github:

![2020-04-11-211349_503x234_scrot](https://user-images.githubusercontent.com/29267777/79052857-c7275080-7c28-11ea-99bf-e1f07a522494.png)

Unless you disable `xpinstall.signatures.required`, the addon *must* be signed by Mozilla, and otherwise doesn't install. However, Mozilla won't sign an extension with a bundled API experiment.

**Comment by numirias** [comment]
I'm gonna close this issue for now because I really don't think this is possible. If you find otherwise, you're more than welcome to reopen.

**Comment by jtagcat** [comment]
Talked with Mozilla people, self-signing is possible, but there isn't any point outside of ESR (what paxmod can be installed on anyway), since the normal version only approves AMO's signatures.
