### ISSUE TITLE
Consider using theme API to simplify extension

### ISSUE THREAD

**Issue by nt1m** [numirias/paxmod#6]
You can use:

```js
browser.theme.update({
  colors: {
    accentcolor: ...,
    textcolor: ...,
    toolbar_field: ...
  }
});
```

While you can only change colors (not the layout or the fonts), the main benefit is that you can get rid of most of your options sheet since browser.theme.update() will update some internal variables that you can re-use in your browser.css stylesheet.

All the stuff you can style can be found here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/theme#colors

This will remove a good amount of CSS in browser.css as well :)

**Comment by numirias** [comment]
After the theme API had put me in a bit of an existential crisis, I indeed managed to throw out a large amount of code. As a result of that, it's now also technically possible to use the extension alongside other themes.

Thanks again for your help.

BTW, I couldn't really get rid of the titlebar UI glitch you told me about in #2 with pure CSS. It seems the event to automatically adjust the dimensions of the inline titlebar doesn't get triggered because a changing height of the toolbox isn't expected. So what I did for now was adding an option to hide the titlebar.

**Comment by nt1m** [comment]
Nice job! Unfortunately, I downloaded v2.0, and it didn't seem to load. Any idea what's happening ?

**Comment by nt1m** [comment]
Oh nevermind, somehow `extensions.legacy.enabled` got switched off.

**Comment by nt1m** [comment]
The new version is a bit flaky, when I switch tabs, the theme gets reset for some reason ?

**Comment by nt1m** [comment]
Ah, another extension was interfering. Envify resets the theme on every tab switch.

**Comment by nt1m** [comment]
It's works pretty nicely so far, thanks :) It works pretty nicely in conjunction with https://mozilla.github.io/FirefoxColor/ btw

**Comment by nt1m** [comment]
Wow, this works extremely well with dynamic themes: https://addons.mozilla.org/en-GB/firefox/collections/ntim/theming-extensions/
